### ISSUE TITLE
UUID support?

### ISSUE THREAD

**Issue by MegaNarwhal** [badbones69/Crazy-Auctions#11]
It appears that the sellers of items are stored by their username in Data.yml. Unless I'm missing something, this means that if a player changes their name, they'll lose ownership of all the items they're currently auctioning/selling and won't get paid for them. Sellers should be stored by their UUID to avoid this.

**Comment by kicjow** [comment]
Hello, yes that is how it is set up. I plan on a recode of Crazy Auctions soon and that will be a main part of it.

**Comment by haloflooder** [comment]
Not sure why uuid support wasn't even thought of in the first place. I would understand if this was around 2013-2014 since name changes were introduced during that time but this is just... crazy...

**Comment by badbones69** [comment]
It was not added as when it was coded I made it for a small server that didn't need that but when it was recorded for public use it slipted my mind. I have not had much time to recode the whole plugin to allow UUIDs but I do plan on it when I get the chance but like I said I don't have much free time to do so.

**Comment by HexedHero** [comment]
We need this.
