### ISSUE TITLE
[Bug Report] Duplication?

### ISSUE THREAD

**Issue by iTaeyeonKim** [badbones69/Crazy-Auctions#111]
**Describe the bug**
Somehow, players are able to "dupe" items (not sure which)

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2
 - Plugin Version: CrazyCrates.v1.10.jar

*Do **NOT** say Latest use `/version crazyauctions` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/NktA0uTp

**Issue**
Not sure how, but I see, player constantly using same commands over and over again.
1. /ah sell 9999
2. /ah
3. /ah expired

**Screenshots**
Sorry, no ss at all

**Comment by badbones69** [comment]
Update
