### ISSUE TITLE
/ah Does not work on 1.8.8

### ISSUE THREAD

**Issue by beautifulpoison** [badbones69/Crazy-Auctions#15]
Skyblock server running 1.8.8 and /ah command wont work? 
Have this plugin on my other 1.12 server and works famously, wanted to add it to my skyblock server but will only run /ca commands. 
Any reason why? Or a fix?

**Comment by kicjow** [comment]
Can you check console to see if there is an error. If so can you pastebin it.

**Comment by beautifulpoison** [comment]
There is no errors, Not when I start the server up or when doing the /ah command

**Comment by kicjow** [comment]
Strange, what happens when they do the command?

**Comment by beautifulpoison** [comment]
Absolutely nothing, won't pull up a menu, says in console the issues the command but no error, no message in chat. 
I just removed an auction plugin to switch to this one and it worked with /ah perfect. Not sure what's going on, your welcome to come on my server and see for yourself if you want to message me for the ip.

**Comment by beautifulpoison** [comment]
Sent an email to the email you have listed

**Comment by beautifulpoison** [comment]
Have you had a chance to look further into this issue?

**Comment by AgentShield233** [comment]
This same thing is happening to me (but my server is in 1.15.2)

**Comment by AgentShield233** [comment]
> This same thing is happening to me (but my server is in 1.15.2)
> /ca works for selling and buying.
> /ca bid doesn't work though, it responds with "null"

/ca bid now works. but the /ah is still broken.
