### ISSUE TITLE
lowering TPS

### ISSUE THREAD

**Issue by Bitconion** [badbones69/Crazy-Auctions#22]
Last update is taking down my server's tps down

     Pct Total	Pct Tick	         Total     Avg	        PerTick  Count    Event
      38.74%	5,927.26%	 44.45 s	 2,963.63 ms	 0.0	       0.0k	    Task: Main$2(interval 100)

There is no command to get debug so i can not post it, and there is no error or warn shown in console.

**Comment by Sakanas** [comment]
I have the same problem

**Comment by Bitconion** [comment]
Saying you have the same problem will not solve it, thats why there is a subscribe button.
