### ISSUE TITLE
Strange symbol "HB SP"

### ISSUE THREAD

**Issue by MrDarkiMC** [badbones69/Crazy-Auctions#27]
version: 1.12
There is a symbol that stands in the middle of the price. I think it's a symbol of non breaking space(but actually i dont know) Screenshot attached below. How i can fix it? i need to replace that symbol "HB SP" to symbol ","
![default](https://user-images.githubusercontent.com/35190267/34648691-fce6b89c-f3b7-11e7-9ac8-723566e7f3ab.png)

**Comment by WinSide** [comment]
#33
