### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by TheSkyless** [badbones69/Crazy-Auctions#34]
Hello,

I 'm having some trouble with the Permissions;
Each time I'm trying to issue the /ah command as non-op, the menu won't open but will give the message "You do not have permission to use this command!' instead.
There is no error message in the server console.

I'm using the Permission System from CloudNet ( https://www.spigotmc.org/resources/cloudnet-the-cloud-network-environment-technology.42059 ).

Thank you very much!

**Comment by Mukunya** [comment]
I have the same problem. I am using essentialsx built in permissions
