### ISSUE TITLE
WARN SPAM

### ISSUE THREAD

**Issue by bosheltuts** [badbones69/Crazy-Auctions#43]
I've used crazy auction in my server, the last version Crazy Auctions v1.2.5.1 in my console im getting this message 

_WARN [CrazyAuctions] com.massivestats.MassiveStats was unable to communicate with its API endpoint._

I'm worried not to lose items my players at some point or crash the plugin, just to know what is this?

**Comment by ArtelGG** [comment]
Update to 1.2.6 and see if it's still happening.

**Comment by Colin13** [comment]
Confirmed still occurring in 1.2.6

**Comment by Colin13** [comment]
I'm having issues loading massivestats.com from Australia.
So is my server located in Canada, I'm guessing this must be an issue with their services & that it would be safe to disable statistics for the time being.

Can anyone confirm/support my claims?

**Comment by kicjow** [comment]
Looking into it at the moment, seems somethings going on with the site.

**Comment by nunavailabul** [comment]
com.massivestats.MassiveStats was unable to communicate with its API endpoint.

Server is in LA

**Comment by badbones69** [comment]
This was fixed make sure to update to the newest CA.

**Comment by Gagels** [comment]
![image](https://user-images.githubusercontent.com/50073332/65490105-d3c2a200-deac-11e9-89da-01b39be64338.png)
Still error

**Comment by badbones69** [comment]
@Gagels that site has been shutdown. CA now uses bstats.
