### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by madtomic** [badbones69/Crazy-Auctions#46]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.876 s
[INFO] Finished at: 2018-09-05T07:19:22-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project crazyauctions: Could not resolve dependencies for project me.badbones69:crazyauctions:jar:1.2.6: Could not find artifact org.spigotmc:spigot:jar:1.12.2-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]

**Comment by Colin13** [comment]
How come you are trying to build? Releases can be downloaded [here](https://www.spigotmc.org/resources/crazy-auctions.25219/)

Otherwise, you need to make sure to have setup your 1.12.2 artifact correctly in your development environment.
