### ISSUE TITLE
Players cannot cancel auctions if they have changed their username.

### ISSUE THREAD

**Issue by mattyokan** [badbones69/Crazy-Auctions#57]
It's been reported to me on a server I work for that players are unable to cancel an auction if they have changed their username between when they created the auction and when they are trying to cancel it.

I would guess this is caused by storing the player's name in the auction storage system instead of their UUID.

Sorry for leaving this as an issue instead of a PR but I don't have time to fix it myself, sorry.

**Comment by mattyokan** [comment]
@badbones69

**Comment by mckite** [comment]
Same problem

**Comment by badbones69** [comment]
This is a known issue as CA does not currently use UUIDs. The plugin will be getting a full recode soon to fix this issue and UUIDs are a top priority as well as the performance with the recode. There is currently no set time frame for when I will recode it but I do plan on it when I get time.
