### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by BrettplayMC** [badbones69/Crazy-Auctions#70]
Version: 1.8.8 Flux (Fork of Paper)
Plugin: 1.2.9
I believe how I did it is that I was in /ah and used the number keys to take an item directly out of the GUI into one of my inventory slots:
![image](https://user-images.githubusercontent.com/20050432/61076555-2201f200-a3e2-11e9-8dea-c31391d0c951.png)

**Comment by badbones69** [comment]
Can you replicate it again? It might be a visual glitch and the item just shows in your inventory but isn't really there. One way to check this is to do it then log out and back in and see if it's still there. Also, Creative mode seems to cause duplication bugs like this so make sure you're not in creative mode.

**Comment by Aurelien30000** [comment]
If your inventory name (for thaïs plugin) contains Colors code, remove  spigot doesn’t support colors with inventory.getName or Title :)
