### ISSUE TITLE
Suggestion: New API Events

### ISSUE THREAD

**Issue by MidnightSugar** [badbones69/Crazy-Auctions#71]
Could you add in events for cancelled and expired auctions?

**Comment by badbones69** [comment]
Added:
- [AuctionCancelledEvent](https://github.com/badbones69/Crazy-Auctions/commit/a33ccb28e9b91dd450e2340240adc7d8d2132607)
- [AuctionExpireEvent](https://github.com/badbones69/Crazy-Auctions/commit/8a0d0b9dfd26ce0c342cb70bd6b0caeca674f3b7)
