### ISSUE TITLE
The server stops responding when someone types /ah

### ISSUE THREAD

**Issue by MCUmbrella** [badbones69/Crazy-Auctions#74]
The first time you enter /ah after the server is started, the server will stop responding for about 2 minutes.
Log file: https://pastebin.com/zWDMqGVA
Messages.yml: https://pastebin.com/D9JBT3hj (Some of the information that can be displayed is translated into Chinese)
config.yml: https://pastebin.com/L2cyK0GQ (Some of the information that can be displayed is translated into Chinese)

**Comment by badbones69** [comment]
Thanks, ill look into it but it could be due to an issue from the fork of spigot your using. I have not seen an issue from normal spigot 1.12.2 servers but ill look into it. Try switching to normal Spigot and see if the issue continues.
Spigot version: git-CatServer-1.12.2-3a7b429 (MC: 1.12.2)

**Comment by MCUmbrella** [comment]
Problem solved after switching to normal Spigot. Thanks very much!
