### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by DjeyMute** [badbones69/Crazy-Auctions#75]
_**Hello,**_ 
Do you know if it is possible to add additional pages in the gui of items that the player on sale because there are only 45 slots ?
And if it is possible also to add a new category for minerals ?
And also to be able to sort the items by date added in the hdv ?
**_Thank you in advance for your answer._**

**Comment by badbones69** [comment]
1. There is a paging system built into CA that you can scroll through at the bottom.
![image](https://user-images.githubusercontent.com/5057118/65737242-e3f4a000-e0ab-11e9-9eb4-99300045d316.png)
2. At the moment categories can not be added unless coded in. It is planned to add custom categories to the plugin.
3. Sorting is also another planned feature for CA.

**Comment by DjeyMute** [comment]
Okay thank you very much for your answers.
But for the "1" I only talk about items that the player sells. He has 45 places and the other items he can not see because there are no other pages.
[https://image.noelshack.com/fichiers/2019/39/5/1569575630-capture-d-ecran-17-li.jpg
](url)

**Comment by badbones69** [comment]
Ah, yes I see now. I'll look into adding that.

**Comment by DjeyMute** [comment]
Thank you very much we all look forward to this ! :)
