### ISSUE TITLE
Event AuctionNewBidEvent not fired

### ISSUE THREAD

**Issue by GCCodes** [badbones69/Crazy-Auctions#85]
Hi there! I tried with a sample code here:
`@EventHandler
    public void onBid(AuctionNewBidEvent e){
        Player p = e.getPlayer();
        p.sendMessage("It works!");
    }`
But it doesn't seem to work. (My plugin is correctly enabled and all of the events are registered)
Here the normal output: https://imgur.com/a/z7Xk1WP

**Comment by badbones69** [comment]
You are calling the wrong event.

- **AuctionNewBidEvent:** This event is fired when a player places a new bid onto an item in the auction house.

You need this one.
- **AuctionListEvent:** his event is fired when a new item is listed onto the auction house.
