### ISSUE TITLE
Crossbow / Trident / Turtle helmet

### ISSUE THREAD

**Issue by dushanbe7** [badbones69/Crazy-Auctions#86]
Hello, I would like to report a bug. These 3 items from 1.14 can be sold as damaged item, even though it's set as false in config ( Allow-Damaged-Items: false ). Thank you.

**Comment by badbones69** [comment]
Thanks for the report. Just fixed: c7c4b878badf0a30b91794a57e2ab399bfa8a46f

**Comment by dushanbe7** [comment]
You rock! Thanks!
