### ISSUE TITLE
Too much times to take bid if starting bid price high

### ISSUE THREAD

**Issue by mckite** [badbones69/Crazy-Auctions#97]
Too much times to take bid if starting bid price high

Such as biding price is 100,000,000,
It will need  100,000 times of add 1000 to bid.

It should be able to bid with command for selected items like “/ah bidAt <price>”

**Comment by badbones69** [comment]
I plan on making the prices customizable when I do a full recode of the plugin. The command is also a planned addition for the bidding option.
